### PR TITLE
Fix checkstyle

### PR DESCRIPTION
**Pull request by pierallard**
- Replace array() by []
- Add @return for each setter
- 1 line comment for class variable
- protected class variables

### CODE REVIEW

**Comment by nidup** [comment]
gtm

**Comment by nidup** [comment]
not GTM, it support php >= 5.3.3

**Comment by nidup** [comment]
we should register on travis to avoid this kind of issues :)

**Comment by jjanvier** [comment]
IMVHO, this library should be PHP 5.6+
We have no reason here to support such an old version of PHP.

Plus this kind of library could be a playground to test (if needed of course) new things.

**Comment by jjanvier** [comment]
we could tag before bumping PHP version @nidup

**Comment by nidup** [comment]
@jjanvier I added travis to ensure the current version works well with PHP 5.3. I'm gonna tag, before to bump, you're right, no reason of keeping a such old version.

**Comment by nidup** [comment]
I tagged a 0.3.0, I merged the following PR https://github.com/akeneo/php-crowdin-api/pull/29 then I tagged 1.0.0-alpha1

@pierallard don't hesitate to rebase your PR on master, you're PR will be GTMable :) Take care if you bump the crowdin translation project from 0.2.0 to 1.0.0@alpha1 because I changed Crowdin namespace to Akeneo\Crowdin.

**Comment by nidup** [comment]
Thx, GTM \o/

**Pull request merged**
