### PR TITLE
Specifying the destination for the download

### PR DESCRIPTION
**Pull request by lologhi**
It fixed my `all.zip` downloading problem
http://guzzle.readthedocs.io/en/latest/request-options.html#sink-option

### CODE REVIEW

**Comment by nidup** [comment]
Hi @lologhi !

Great! It fixes an issue I encountered here https://github.com/akeneo/nelson/issues/12 !
:tada: thank you again for your valuable contribution :tada: 
Do you need a 1.0.0-alpha4 tag with this couple of fixes?

**Comment by lologhi** [comment]
Great! Yep, I'd like a tag to fix my project 😁

**Comment by nidup** [comment]
Hi @lologhi I just released the alpha4, thanks again for the fixes :tada: 
Have a good day!

**Comment by lologhi** [comment]
Great, thank you @nidup. (Hope I haven't broken other things 💭)

**Pull request merged**
