### PR TITLE
Switch to Crowdin new domain

### PR DESCRIPTION
**Pull request by lologhi**
Because my `GET
https://api.crowdin.net/api/project/project-name/export?key=MYSECRETAPIKEY` was returning `502 Bad Gateway`. And switching to api.crowdin.com fixed the situation.

### CODE REVIEW

**Comment by lologhi** [comment]
Result is not coming back from ScrutinizerCI, but it's ok : https://scrutinizer-ci.com/g/akeneo/php-crowdin-api/inspections/ebe25530-e060-4337-98f6-350535ec77ba

**Comment by nidup** [comment]
Hi @lologhi 

Thank you for the PR! :tada: :tada:

**Comment by lologhi** [comment]
No problemo!

**Comment by nidup** [comment]
Just released the alpha6 including this fix!
Thx again and have a good day!

**Pull request merged**
