### PR TITLE
Allow passing additional parameters to UpdateFile

### PR DESCRIPTION
**Pull request by winzou**
Hi,

Cf. https://crowdin.com/page/api/update-file

I cannot use the lib if I cannot set the `update_option` in the API call (default is to delete translations when a key changes...!)

Thanks

### CODE REVIEW

**Comment by nidup** [comment]
Hi @winzou 
Thank you for your PR!
Imho, the $data array seems inconsistent with other API methods, if we would do so i would add it on the ApiInterface method.
I would prefer add a setUpdateOption($mode) in the UpdateFile, to be able to do:
```
$api = $client->api('update-file');
$source = '/tmp/update-crowdin';
$file   = 'src/Pim/Bundle/CatalogBundle/Resources/translations/messages.en.yml';
$api->addFile($file, $source.'/'.$file);
$api->setUpdateOption('update_as_unapproved');
$result = $api->execute();
echo $result
```
Please change your PR and add related spec and i will merge it.
Thank you!

**Comment by winzou** [comment]
Hi,

I have actually changed the approach to be able to set parameters for every api call. There are a lot of them and it won't be smart to define a method for each and every parameter.

**Comment by winzou** [comment]
ping @nidup is this new approach ok for you ?

**Comment by nidup** [comment]
Hello @winzou!
Sorry for the delay, i'm in holidays ;)
At first view, the set of parameters looks imvho less OOP and less human readable (i personaly try to avoid it when i can but at the end I often use it for extensibility purpose), in other hand it helps to quickly and easily cover the new options of Crowdin API and it's maybe the most important for an open source library.
So, i do agree with this new approach, thank you to implem and spec (at least the options you need) and i'll merge it.
Thank you!

**Comment by winzou** [comment]
Done :)

**Comment by lologhi** [comment]
Yeah ! :+1:

**Pull request merged**
